image: debian

test:
  script:
    - apt-get update
    - apt-get -y install git build-essential pkg-config libsodium-dev clang curl
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly"
    - source $HOME/.cargo/env
    - cargo install cbindgen

    - cd tests/native
    # The current Makefile setup fails to consider the vpaths intgroduced in
    # Makefile.libcose made available at lib build time; calling make in
    # different steps works around that.
    - make libs
    - make test-all-versions

    # Build test using RIOT
    # Run the build process for the IoT-LAB demo
    # wget, unzip not really expected to be used -- but RIOT's build system just expects them to be there.
    - apt-get -y install gcc-arm-none-eabi binutils-multiarch python3 wget unzip
    - git submodule init && git submodule update
    - cd ../riot-tests/plugtest-server
    - make BOARD=iotlab-m3 all

pages:
  script:
    - apt-get update && apt-get -y install doxygen graphviz
    - cd doc && doxygen Doxyfile && cd ..
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

