# FIXME: the sodium.o name is hardcoded as this makefile uses vpath while libcose works from source names
libs/libcose/makefiles/sodium.mk: libs
include libs/libcose/makefiles/sodium.mk

CPPFLAGS += -I../backends/libcose/inc/
CPPFLAGS += -Ilibs/libcose/include/
CPPFLAGS += -Ilibs/nanocbor/include/

vpath %.c ../backends/libcose/src/
vpath %.c libs/libcose/src/
vpath %.c libs/libcose/src/crypt/

CFLAGS += ${CFLAGS_CRYPTO}
LDFLAGS += ${LDFLAGS_CRYPTO}

BACKEND_OBJS += libcose.o cose_crypto.o sodium.o $(shell pkg-config --libs $(SODIUM_LIB))
