BACKEND_OBJS += ../../rust/liboscore-backends-standalone/target/debug/libliboscore_backends_standalone.a

../../rust/liboscore-backends-standalone/target/debug/libliboscore_backends_standalone.a: always
	cd ../../rust/liboscore-backends-standalone && cargo +nightly build

rustbuilthdr/oscore_native/crypto_type.h:
	mkdir -p $$(dirname $@)
	(cd ../../rust/liboscore-cryptobackend/ && cbindgen --lang=C) > $@

cryptobackend-aead.o cryptobackend-hkdf.o: rustbuilthdr/oscore_native/crypto_type.h

CPPFLAGS += -I rustbuilthdr/

CFLAGS += -I../../rust/liboscore-backends-standalone/c-headers/

.PHONY: always
