APPLICATION ?= test_$(notdir $(subst -,_,$(patsubst %/,%,$(CURDIR))))

RIOTBASE ?= $(CURDIR)/../RIOT

BOARD ?= native

DEVELHELP ?= 1

# C11 features are accepted in the OSCORE implementation, but that causes
# pedantic Werrors to show up in RIOT source; gnu11 seems to ignore those.
CFLAGS += -std=gnu11

EXTERNAL_MODULE_DIRS += $(abspath ../../..)/backends/riot-modules
USEMODULE += oscore

# Pick a backend; without, no algorithms are available
USEMODULE += libcose_crypt_hacl
# Add tinydtls backend for AES-CCM and HKDF support.
#
# As this is waiting for https://github.com/bergzand/libcose/pull/91 and /94,
# it needs the following lines adapted in RIOT:
#
# In tests/riot-tests/RIOT/pkg/libcose/Makefile, set:
#
# PKG_URL=https://github.com/chrysn-pull-requests/libcose
# PKG_VERSION=f4eb5b54c48a2985512bf9e83587bf7b2ec90fb4
#
# (This picks a recent commit from the liboscore-vendor branch).
USEMODULE += libcose_crypt_tinydtls
# and we'll have to pick one of those recently...
USEMODULE += prng_sha256prng

EXTERNAL_MODULE_DIRS += $(abspath ..)/

TESTS = ../test-evaluator.sh

# workarounds for https://github.com/RIOT-OS/RIOT/issues/13121
USEMODULE += gnrc_sock
USEMODULE += gnrc_ipv6

include $(RIOTBASE)/Makefile.include
