APPLICATION ?= test_$(notdir $(subst -,_,$(patsubst %/,%,$(CURDIR))))

RIOTBASE ?= $(CURDIR)/../RIOT

BOARD ?= native

DEVELHELP ?= 1

# C11 features are accepted in the OSCORE implementation, but that causes
# pedantic Werrors to show up in RIOT source; gnu11 seems to ignore those.
CFLAGS += -std=gnu11

EXTERNAL_MODULE_DIRS += $(abspath ../../..)/backends/riot-module
USEMODULE += oscore

EXTERNAL_MODULE_DIRS += $(abspath ..)/testwrapper

TESTS = ../test-evaluator.sh

include $(RIOTBASE)/Makefile.include
