# First inclusion is exactly when there is this file at the end of
# MAKEFILE_LIST, fix the value rather than reevaluating this expression at any
# possible time
OSCOREBASE := $(abspath $(lastword $(MAKEFILE_LIST))/../../../..)

# OSCORE's own includes
INCLUDES += -I${OSCOREBASE}/src/include

# Backends we choose for RIOT
INCLUDES += -I${OSCOREBASE}/backends/nanocoap/inc

ifeq (libcose,${OSCORE_CRYPTO_BACKEND})
INCLUDES += -I${OSCOREBASE}/backends/libcose/inc
endif
ifeq (rust,${OSCORE_CRYPTO_BACKEND})
INCLUDES += -I${OSCOREBASE}/rust/liboscore-cryptobackend-aead/c-headers

BASELIBS += ${OSCOREBASE}/rust/liboscore-cryptobackend-aead-standalone/target/i686-unknown-linux-gnu/debug/libliboscore_cryptobackend_aead_standalone.a

${OSCOREBASE}/rust/liboscore-cryptobackend-aead-standalone/target/i686-unknown-linux-gnu/debug/libliboscore_cryptobackend_aead_standalone.a:
	cd ${OSCOREBASE}/rust/liboscore-cryptobackend-aead-standalone/ && cargo +nightly build --target=i686-unknown-linux-gnu

.PHONY: ${OSCOREBASE}/rust/liboscore-cryptobackend-aead-standalone/target/i686-unknown-linux-gnu/debug/libliboscore_cryptobackend_aead_standalone.a
endif
